# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploy to WP Engine
on:
    workflow_call:
        inputs:
            WPE_ENV:
                type: string
                description: 'The WP Engine environment to deploy to.'
                required: true
            asset_folder_name:
                type: string
                default: 'dist'
                description: 'The name of the folder that gets generated in the build step. Default: dist'
                required: false
            theme_name:
                type: string
                default: 'cno-starter-theme'
                description: 'The name of the theme to deploy. Default: cno-starter-theme'
                required: false

# Cancel all previous workflow runs for the same branch that have not yet completed.
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    bundle:
        name: Bundle Assets
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4

            - name: Install NPM dependencies
              run: npm ci

            - name: Build assets
              run: npm run build

            - name: Upload dist folder
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ inputs.asset_folder_name }}
                  path: wp-content/themes/${{ inputs.theme_name }}/${{ inputs.asset_folder_name }}

    deploy:
        name: Deploy to WP Engine
        runs-on: ubuntu-latest
        needs: [bundle]
        steps:
            - uses: actions/checkout@v4
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: ${{ inputs.asset_folder_name }}
                  path: wp-content/themes/${{ inputs.theme_name }}/${{ inputs.asset_folder_name }}
            - name: GitHub Action Deploy to WP Engine
              if: success()
              uses: wpengine/github-action-wpe-site-deploy@v3
              with:
                  WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
                  WPE_ENV: ${{ inputs.WPE_ENV }}
