name: PHPUnit Tests

on:
  workflow_call:
    inputs:
      should_deploy_coverage:
        type: boolean
        description: "Whether to deploy code coverage to GitHub Pages if tests pass."
        required: false
        default: true

jobs:
  phpunit:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ["8.2", "8.4"]
    services:
      database:
        image: mysql:latest
        env:
          MYSQL_DATABASE: wordpress_tests
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
    steps:
      - name: Check out source code
        uses: actions/checkout@main

      - name: Install SVN
        run: sudo apt-get update && sudo apt-get install -y subversion

      - name: Install Composer
        run: |
          EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)"
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          ACTUAL_SIGNATURE="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
          if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]; then
            >&2 echo 'ERROR: Invalid installer signature'
            rm composer-setup.php
            exit 1
          fi
          php composer-setup.php --quiet
          rm composer-setup.php
          mv composer.phar /usr/local/bin/composer

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-versions }}
          tools: phpunit-polyfills:1.1

      - name: Setup tests
        run: bash bin/gh-install-wp-tests.sh wordpress_tests root root 127.0.0.1 latest true

      - name: Run tests
        run: phpunit

      - name: Upload HTML Coverage Artifact
        if: matrix.php-versions == '8.2' && inputs.should_deploy_coverage == true
        uses: actions/upload-artifact@main
        with:
          name: html-coverage
          path: html-coverage

  # Deploy HTML coverage to GitHub Pages after tests pass on main
  deploy-coverage:
    name: Deploy HTML Coverage to GitHub Pages
    needs: phpunit
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && inputs.should_deploy_coverage == true
    steps:
      - name: Download HTML Coverage Artifact
        uses: actions/download-artifact@main
        with:
          name: html-coverage
          path: html-coverage

      - name: Copy html-coverage to public
        run: |
          rm -rf public || true
          cp -r html-coverage public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
