# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: PHPCS check
on:
    workflow_call:

jobs:
    phpcs:
        name: PHPCS check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: 'shivammathur/setup-php@v2'
              with:
                  php-version: 'latest'
                  ini-values: memory_limit=256M'
                  coverage: none
                  tools: cs2pr

            - name: Check for composer.json
              id: composer_json_check
              run: |
                  if [ ! -f composer.json ]; then
                    echo "composer.json not found. Skipping Composer install."
                    echo "skip_composer=true" >> $GITHUB_ENV
                  else
                    echo "skip_composer=false" >> $GITHUB_ENV
                  fi

            - name: Install Composer dependencies
              if: env.skip_composer == 'false'
              uses: 'ramsey/composer-install@v3'
              with:
                  # Bust the cache at least once a month - output format: YYYY-MM.
                  custom-cache-suffix: $(date -u "+%Y-%m")

            - name: Run PHPCS Beautifier
              id: phpcbf
              if: env.skip_composer == 'false'
              continue-on-error: true
              run: composer phpcbf

            - name: Run PHPCS checks
              id: phpcs
              if: env.skip_composer == 'false'
              run: composer phpcs

            - name: Show PHPCS results in PR
              if: ${{ always() && steps.phpcs.outcome == 'failure' }}
              run: cs2pr ./phpcs-report.xml
